networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    container_name: db-shopper-api
    image: bitnami/postgresql:14.11.0-debian-12-r11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-shopper-api
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    container_name: shopper-api
    build: .
    ports:
      - "3000:3000"
    environment:
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      DATABASE_URL: "postgresql://postgres:postgres@db-shopper-api:5432/db-shopper-api"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork
    command: >
      sh -c "npm run migrate && npm start"
