version: '3.7'

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    container_name: db-shopper-api
    image: bitnami/postgresql:14.11.0-debian-12-r11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-shopper-api
    networks:
      - mynetwork